spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
    show-sql: true

jwt:
  secret-key: EtXEwAAJjHfjirNCeftqqqF9RheVbc57hgCt3ERJ9ojYEAkYkwGdiRKY3OuHoWAGDBuMrgvNT4rZ3u9+AZGnag==
  access-expiration-time: 1800000
  refresh-expiration-time: 604800000

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    com.my.foody: DEBUG
